

services:
  postgres:
    image: postgres:15-alpine
    container_name: contacts_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ftp-server:
    image: delfer/alpine-ftp-server
    container_name: contacts_ftp_container
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=user|pass
      - ADDRESS=localhost
    restart: always

volumes:
  postgres_data:
